# Concluding Remarks {#conclusion}

My hope is that this book provides a nice introduction into understanding how statisticians, data scientists, and many other professionals use RStudio and R Markdown to simplify their analyses and ensure that their reports are computationally reproducible. Learning R is not nearly as intimidating as it once was, and more and more industries are shifting towards free open-source tools like R and RStudio. R Markdown provides an excellent way to document your analyses and share it with others in a variety of formats.

Of course, this book is just the tip of the iceberg in terms of showing you what R can really do. If you'd like to learn more, I encourage you to check out [Modern Dive](http://www.moderndive.com/), a free, online, open-source book Albert Kim and I wrote on using modern data analysis techniques and visualization with R, RStudio, and R Markdown. It was updated to a Second Edition in Fall 2024, and it is available at https://www.moderndive.com/v2/. The Second Edition will be published by CRC Press in early 2025, and [the First Edition was published](https://www.routledge.com/Statistical-Inference-via-Data-Science-A-ModernDive-into-R-and-the-Tidyverse/Ismay-Kim/p/book/9780367409821?srsltid=AfmBOoqLasBhcQVciOoGIeKfZ-kdfG2KwkcXISwn-D8_u8Zku7Z8FqKd) in late 2019.

Additionally, Garrett Grolemund's "Hands-On Programming with R" [@handson2014] is an excellent resource and goes into much more depth than I do here on how to work with more complicated objects in R. It also discusses concepts in a project-based framework that is entertaining and easy-to-read.

As always, feel free to send me an email at <chester.ismay@gmail.com> if you'd like any further clarification or if you have suggestions on improvements. Thanks for taking the time to read through this and best wishes to you on your next steps towards reproducible, thoughtful, beautiful analyses!

`-` Chester
