# Concluding Remarks {#conclusion}

I hope that this book provides a nice gateway into understanding how statisticians, 
data scientists, and many other professionals use RStudio and R Markdown to simplify
their analyses and to ensure that their reports are computationally reproducible.
Learning R is nowhere near as intimidating as it used to be and more and more
industries are shifting towards free open-source tools like R and RStudio.  R Markdown
provides an excellent way to document your analyses and share it with others in a
variety of formats.

Of course, this book is just the tip of the iceberg in terms of showing you what R
can really do.  If you'd like to learn more I encourage you to check out Albert Kim
and I's online, free, open-source book on using modern data analysis techniques
and visualization with R, RStudio, and R Markdown.  More details on that project
will be coming soon.

Additionally, Garrett Grolemund's "Hands-On Programming with R" [@handson2014] is an excellent resource and goes into more depth than I do here as to how to work with more
complicated objects in R.  It also discusses concepts in a project-based framework
that is entertaining and easy-to-read.

As always, feel free to send me an email at <chester.ismay@gmail.com> if you'd
like any further clarification or if you have suggestions on improvements.  Thanks
for taking the time to read through this and best wishes to you on your next
steps towards reproducible, thoughtful, beautiful analyses!

`-` Chester